version: '2'
services:
  web:
    build: .
    ports:
     - "5000:5000"
    links:
     - mysql
    volumes:
     - .:/code
  mysql:
    image: "mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    expose:
      - 3306
